@startuml AllOverview
title SSBD Core Ontology – Overview
skinparam classAttributeIconSize 0
skinparam classFontColor automatic
skinparam classHeaderBackgroundColor #ADD8E6


class SSBD_Project {
    +project_name
    +project_type
    +license
  }


package "Repository Information" {
class SSBD_dataset {
    +ID
    +dataset_title
    +description
    +file_sets_url
    +file_format
    +dataset_type
    +folder_name
  }

  class paper_information {
    +paper_title
    +paper_doi
    +paper_url
    +paper_info
    +MesH_terms
}
  class agent_person_information {
    +role 
    +first_name
    +last_name
    +middle_name
    +email
    +organization
    +department
    +address
    +phone
    +ORCID
    +researchermap_id
    +J_Global_id
  }
}
 
package "Biological Background" {
  class SSBD_biosample_information
  SSBD_biosample_information --> "0..*" NCBITaxon_Organism : is_about_organism
  SSBD_biosample_information --> "0..*" Strain : is_about_strain
  SSBD_biosample_information --> "0..*" CL_Cell : is_about_cell
  SSBD_biosample_information --> "0..*" UBERON_Anatomy : is_about_anatomical_entity
  SSBD_biosample_information --> "0..*" GO_Term : is_about_GO_bp / cc / mf
  SSBD_biosample_information --> "0..*" intrinsic_variable : has_intrinsic_variable
  SSBD_biosample_information --> "0..*" extrinsic_variable : has_extrinsic_variable
  SSBD_biosample_information --> "0..*" MeSH_TopicalDescriptor : has_MeSH_ID

 class SSBD_genetic_modification{
    +gene_name
    +Ensembl_gene_ID
    +Uniprot_ID
    +genetic_modification_method
    +detected_signal
    +detected_method
    +tag_uri
    +genotype
    +oligo_primer
  }

  class SSBD_reagent_information{
    +reagent_term
    +reagent_url
    +concentration
    +concentration_unit
    +fold_dilution
    +fold_dilution
  }
}

package "Imaging Setup" {
  class SSBD_imaging_method_information{
    +contrast_enhancing_method
    +detection_method
    +visualization_method
    +illumination_method
    +source of_contrast
    +contrast_enhancing_method
    +resolution_enhancing_method
    +imaged_parameter
  }
  class SSBD_imaging_instruments{
    +body
    +module
    +light_source
    +detector
    +objective
    +filter_set
    +dichroic
  }
  class SSBD_OME_NGFF_info {
    +s3_endpoint_url
    +thumnbnail_url
    +vizarr_url
    +axes
    +xyzct
  }
  class SSBD_dimension_data{
    +Xscale
    +Yscale
    +Zscale
    +Tscale
  }
}

' --- relations ---
SSBD_Project -- "1..*" SSBD_dataset : RO:0002234 (has output)
SSBD_Project -- "1..*" paper_information : has_paper_information
SSBD_Project -- "1..*" agent_person_information : has_agent_person_informatio
SSBD_dataset -- "1" SSBD_biosample_information : has_biosample_information
SSBD_dataset -- "0..1" SSBD_imaging_method_information : has_imaging_method_information
SSBD_dataset -- "0..1" SSBD_imaging_instruments : has_instrument_information
SSBD_dataset -- "1" SSBD_OME_NGFF_info : RO:0002180
SSBD_dataset -- "0..1" SSBD_dimension_data : has_dimension_information
SSBD_biosample_information -- "0..*" SSBD_genetic_modification : has_genetic_modification
SSBD_biosample_information -- "0..*" SSBD_reagent_information : has_reagent_information
@enduml
